# -*- coding: utf-8 -*-
"""Data_Cleaning_in_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNz08QYRRxpeRCCk-2471z9QSe_IbeMM

# **Data Cleaning in Pandas**
"""

import pandas as pd

df = pd.read_excel('/content/Customer Call List.xlsx')

df

df = df.drop_duplicates()
df

df = df.drop(columns = 'Not_Useful_Column')
df

#df['Last_Name'] = df['Last_Name'].str.lstrip('...')
#df['Last_Name'] = df['Last_Name'].str.lstrip('/')
#df['Last_Name'] = df['Last_Name'].str.rstrip('_')

df['Last_Name'] = df['Last_Name'].str.strip('./_')
df

df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))

df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '', regex = True)
df

df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-'+ x[3:6] + '-' + x[6:10])
df

df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '', regex = True)
df['Phone_Number'] = df['Phone_Number'].str.replace('Na--', '', regex = True)
df

df

df[['Street_Address', 'State', 'Zip_Code']]=df['Address'].str.split(',',n=2, expand=True)
df

df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')
df

df['Do_Not_Contact']= df['Do_Not_Contact'].str.replace('Yes', 'Y')
df['Do_Not_Contact']= df['Do_Not_Contact'].str.replace('No', 'N')
df

df.fillna('' , inplace = True)
df

for x in df.index:
  if df.loc[x, 'Do_Not_Contact'] == 'Y':
    df.drop(x, inplace= True)

df

for x in df.index:
  if df.loc[x, 'Do_Not_Contact'] == '':
    df.drop(x, inplace= True)

df

for x in df.index:
  if df.loc[x, 'Phone_Number'] == '':
    df.drop(x, inplace= True)

df

#Another way to drop null Values
#df = df.dropna(subset='Phone_Number'), inplace = True

df = df.reset_index(drop = True)
df

