# -*- coding: utf-8 -*-
"""Exploratory_Data Analysis_in_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_9Br-rO9povK7j0uGNxCVuZbe0sjp6B

# **Exploratory Data Analysis in Pandas**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/world_population.csv')
df

pd.set_option('display.float.format', lambda x: '%.2f' % x)

df

df.info()

df.describe()

df.isnull().sum()

df.nunique()

df.sort_values(by='2022 Population',ascending = False).head(10)

df.sort_values(by='World Population Percentage',ascending = False).head(10)

df.corr(numeric_only=True)

sns.heatmap(df.corr(numeric_only= True), annot = True)
plt.rcParams['figure.figsize'] = (20,10)
plt.show()

df.groupby('Continent').mean(numeric_only= True).sort_values(by = '2022 Population', ascending = False)

df[df['Continent'].str.contains('Oceania')]

df2 = df.groupby('Continent')[['1970 Population',
       '1980 Population', '1990 Population', '2000 Population',
       '2010 Population', '2015 Population', '2020 Population',
       '2022 Population']].mean(numeric_only= True).sort_values(by = '2022 Population', ascending = False)
df2

df.columns

df3 = df2.transpose()
df3

df3.plot()

df.boxplot(figsize= (22,10))

df.dtypes

df.select_dtypes(include = 'float64')

