# -*- coding: utf-8 -*-
"""Filtering_and_Ordering_in_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxJ_g7lTHvgb7DvjQ7rlOGxRpK54U3iv

# **Filtering and Ordering in Pandas**
"""

import pandas  as  pd

df = pd.read_csv("/content/world_population.csv")

df

df[df['Rank']<= 10]

specfic_countries = ['Bangladesh','Brazil']
df[df['Country'].isin(specfic_countries)]

df[df['Country'] . str.contains('United')]

df2 = df.set_index('Country')
df2

df2.filter(items = ['Continent', 'CCA3'], axis = 1)

df2.filter(items = ['Zimbabwe'], axis = 0)

df2.filter(like = 'United', axis = 0)

df2.loc['United States']

df2.iloc[3]

df

df[df['Rank'] < 10] . sort_values(by = 'Rank', ascending = False)

df[df['Rank'] < 10] .sort_values(by=['Continent', 'Country'],ascending=[False,True])

