# -*- coding: utf-8 -*-
"""Group_by_and_Aggregating_in_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15G7qksX8d8MOOWRLwIcntaeRj75r09ms

# **Group by and Aggregating**
"""

import pandas as pd

df = pd.read_csv("/content/Flavors.csv")

df

group_by_frame =  df.groupby('Base Flavor')

group_by_frame.mean(numeric_only= True)

df.groupby('Base Flavor').mean(numeric_only=True)

df.groupby('Base Flavor').count()

df.groupby('Base Flavor').min()

df.groupby('Base Flavor').max()

df.groupby('Base Flavor').sum(numeric_only = True)

df.groupby('Base Flavor').agg({'Flavor Rating' : ['mean','sum','max','count'], 'Texture Rating':['mean','sum','count']})

df

df.groupby(['Base Flavor','Liked']).mean(numeric_only=True)

df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating' : ['mean','sum','max','count']})

df.groupby('Base Flavor').describe().T

