# -*- coding: utf-8 -*-
"""Indexing_in_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E32bzRYDe3A2wFR0glk1Oj_yqK3Z7CXQ
"""

import pandas as pd

df = pd.read_csv("/content/world_population.csv")

df

df = pd.read_csv("/content/world_population.csv", index_col = 'Country')

df

df.reset_index(inplace = True)

df

df.set_index('Country', inplace= True)

df

df.loc['Algeria']

df.iloc[2]

df.reset_index(inplace= True)

df.set_index(['Continent','Country'], inplace =  True)

df

df.head(10)

df.sort_index(ascending = [False, True])
#pd.set_option('display.max.row',235)

df.loc['Africa','Angola']

df.iloc[1]

