# -*- coding: utf-8 -*-
"""Merge_Join_and_Concatenate_in_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJQMx_q4PJNbSSqQC6U2YG2OptRUNXMZ

# **Merge, Join, and Concatenate in Pandas**
"""

import pandas as pd

df1 = pd.read_csv("/content/LOTR.csv")
df1

df2 = pd.read_csv('/content/LOTR 2.csv')
df2

df1.merge(df2 , how = 'inner' , on = ['FellowshipID', 'FirstName'])

df1.merge(df2 , how='outer')

df1.merge(df2 , how='left')

df1.merge(df2 , how='right')

df1.merge(df2 , how='cross')

df1.join(df2, on = 'FellowshipID', how = 'outer' , lsuffix = '_Left', rsuffix = '_Right')

df4 = df1.set_index('FellowshipID').join(df2.set_index('FellowshipID'),how = 'outer' , lsuffix = '_Left', rsuffix = '_Right')

df4

pd.concat([df1,df2], join = 'inner', axis = 1)



