# -*- coding: utf-8 -*-
"""Pandas_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QuWgzdvqZDmg-8l8Hwu53HCpevVoOvT

# **Pandas Visualization**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Ice Cream Ratings.csv')
df = df.set_index('Date')
df

print(plt.style.available)
plt.style.use('fivethirtyeight')

df.plot()

Ddf.plot(kind = 'line', subplots= True, figsize = (10,5))

"""# **Line Chart**"""

df.plot(kind = 'line' , title = 'Ice Cream Ratings', xlabel = 'Date', ylabel = 'Rating')

"""# **Bar Charts**"""

#bar chart
df.plot(kind = 'bar')

#stacked Bar
df.plot(kind = 'bar', stacked = True)

df['Flavor Rating'].plot(kind = 'bar', stacked = True)

#Vertical Bar CHart
df.plot.barh()

#Vertical Stacked Bar CHart
df.plot.barh(stacked = True)

"""# **Scatter Chart**"""

df.plot.scatter( x= 'Flavor Rating' , y = 'Overall Rating' , s=500 , c= 'Pink')

"""# **Histogram Chart**"""

df.plot.hist(bins = 10 , edgecolor = 'black')

"""# **Box Plot**"""

df.plot.box()

"""# **Area Plot**"""

df.plot.area(figsize = (10,5))

"""# **Pie Chart**"""

df.plot.pie(y = 'Flavor Rating' , figsize = (10,7))

